import Vue from 'vue'
import {complexQueryDec0, complexQueryDec3, complexQueryDec5, complexQueryDec7} from '../common/sortMethods'

export const fixedColumns = [ // 固定需要展示列
  {
    id: '1',
    minWidth: '100px',
    label: '交易日期',
    field: 'trade_date',
    align: 'left',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortByChineseCharacters.bind(Vue, 'trade_date')
  },
  {
    id: '2',
    minWidth: '100px',
    label: '股东账户',
    field: 'acct_id',
    align: 'left',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortByChineseCharacters.bind(Vue, 'acct_id')
  },
  {
    id: '3',
    minWidth: '100px',
    label: '股东名称',
    field: 'acct_name',
    align: 'left',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortByChineseCharacters.bind(Vue, 'acct_name')
  },
  {
    id: '4',
    minWidth: '100px',
    label: '证券代码',
    field: 'sec_code',
    align: 'left',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'sec_code')
  },
  {
    id: '5',
    minWidth: '100px',
    label: '证券简称',
    field: 'sec_name',
    align: 'left',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortByChineseCharacters.bind(Vue, 'sec_name')
  },
  {
    id: '6',
    minWidth: '100px',
    label: '订单时间',
    field: 'order_time',
    align: 'left',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortByChineseCharacters.bind(Vue, 'order_time')
  },
  {
    id: '7',
    minWidth: '100px',
    label: '订单时间秒后小数',
    field: 'order_time_dec',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'order_time_dec'),
    formatter: complexQueryDec7,
    format: '#,##0.0000000'
  },
  {
    id: '8',
    minWidth: '100px',
    label: '订单编号',
    field: 'order_no',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'order_no'),
    format: '0'
  },
  {
    id: '9',
    minWidth: '100px',
    label: '申报数量',
    field: 'order_vol',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'order_vol'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    id: '10',
    minWidth: '100px',
    label: '申报价格',
    field: 'order_price',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'order_price'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    id: '11',
    minWidth: '100px',
    label: '申报前市场最新成交价',
    field: 'bo_trade_price',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_trade_price'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    id: '12',
    minWidth: '100px',
    label: '申报后订单所在档位',
    field: 'ao_price_rank',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_price_rank')
  },
  {
    id: '13',
    minWidth: '100px',
    label: '申报后与该订单同向同档位其他账户申报数量',
    field: 'ao_same_dir_other_vol_5',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_same_dir_other_vol_5'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    id: '14',
    minWidth: '100px',
    label: '申报后与该订单同向前五档其他账户申报数量',
    field: 'ao_same_dir_other_vol_10',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_same_dir_other_vol_10'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    id: '15',
    minWidth: '100px',
    label: '申报后与该订单同向前十档其他账户申报数量',
    field: 'ao_other_vol_10',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_other_vol_10'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    id: '16',
    minWidth: '100px',
    label: '信用标签',
    field: 'credit_type',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortByChineseCharacters.bind(Vue, 'credit_type')
  },
  {
    id: '17',
    minWidth: '100px',
    label: '买卖方向',
    field: 'trade_dir',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortByChineseCharacters.bind(Vue, 'trade_dir')
  },
  {
    id: '18',
    minWidth: '100px',
    label: '订单类型',
    field: 'order_type',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortByChineseCharacters.bind(Vue, 'order_type')
  },
  {
    id: '19',
    minWidth: '100px',
    label: '该订单成交数量',
    field: 'trade_vol',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'trade_vol'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    id: '20',
    minWidth: '100px',
    label: '该订单成交金额',
    field: 'trade_amt',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'trade_amt'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    id: '21',
    minWidth: '100px',
    label: '该订单成交笔数',
    field: 'trade_cnt',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'trade_cnt'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    id: '22',
    minWidth: '100px',
    label: '订单成交标志',
    field: 'trade_flag',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortByChineseCharacters.bind(Vue, 'trade_flag')
  },
  {
    id: '23',
    minWidth: '100px',
    label: '撤单数量',
    field: 'withdraw_vol',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'withdraw_vol'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    id: '24',
    minWidth: '100px',
    label: '撤单时间',
    field: 'withdraw_time',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortByChineseCharacters.bind(Vue, 'withdraw_time')
  },
  {
    id: '25',
    minWidth: '100px',
    label: '撤单时间秒后小数',
    field: 'withdraw_time_dec',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'withdraw_time_dec'),
    formatter: complexQueryDec7,
    format: '#,##0.0000000'
  },
  {
    id: '26',
    minWidth: '100px',
    label: '撤单前市场最新成交价',
    field: 'bw_trade_price',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_trade_price'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    id: '27',
    minWidth: '100px',
    label: '撤单前订单所在档位',
    field: 'bw_price_rank',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_price_rank')
  },
  {
    id: '28',
    minWidth: '100px',
    label: '撤单前与该订单同向同档位其他账户申报数量',
    field: 'bw_same_rank_other_vol',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_same_rank_other_vol'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    id: '29',
    minWidth: '100px',
    label: '撤单前与该订单同向前五档其他账户申报数量',
    field: 'bw_same_dir_other_vol_5',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_same_dir_other_vol_5'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    id: '30',
    minWidth: '100px',
    label: '撤单前与该订单同向前十档其他账户申报数量',
    field: 'bw_same_dir_other_vol_10',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_same_dir_other_vol_10'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    id: '31',
    minWidth: '100px',
    label: '该订单第一笔成交价格',
    field: 'first_trade_price',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'first_trade_price'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    id: '32',
    minWidth: '100px',
    label: '该订单最后一笔成交价格',
    field: 'last_trade_price',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'last_trade_price'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    id: '33',
    minWidth: '100px',
    label: '该订单第一笔成交时间',
    field: 'first_trade_time',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortByChineseCharacters.bind(Vue, 'first_trade_time')
  },
  {
    id: '34',
    minWidth: '100px',
    label: '该订单第一笔成交时间秒后小数',
    field: 'first_trade_time_dec',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'first_trade_time_dec'),
    formatter: complexQueryDec7,
    format: '#,##0.0000000'
  },
  {
    id: '35',
    minWidth: '100px',
    label: '该订单最后一笔成交时间',
    field: 'last_trade_time',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortByChineseCharacters.bind(Vue, 'last_trade_time')
  },
  {
    id: '36',
    minWidth: '100px',
    label: '该订单最后一笔成交时间秒后小数',
    field: 'last_trade_time_dec',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'last_trade_time_dec'),
    formatter: complexQueryDec7,
    format: '#,##0.0000000'
  },
  {
    id: '37',
    minWidth: '100px',
    label: '该订单成交时段内该证券市场成交均价',
    field: 'sec_trade_price',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'sec_trade_price'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    id: '38',
    minWidth: '100px',
    label: '该订单成交时段内该证券市场成交数量',
    field: 'sec_trade_vol',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'sec_trade_vol'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    id: '39',
    minWidth: '100px',
    label: '该订单成交时段内该证券市场成交金额',
    field: 'sec_trade_amt',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'sec_trade_amt'),
    formatter: complexQueryDec3,
    format: '#,##0.000'
  },
  {
    id: '40',
    minWidth: '100px',
    label: '该订单第一笔成交前一笔成交价格',
    field: 'first_trade_pre_price',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'first_trade_pre_price'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    id: '41',
    minWidth: '100px',
    label: '该订单最后一笔成交后一笔成交价格',
    field: 'last_trade_next_price',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'last_trade_next_price'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  }
]

export const gearColumns = [ // 档位列
  {
    show: false,
    gear: 1,
    id: '201',
    minWidth: '100px',
    label: '申报前买方第一档价格',
    field: 'bo_buy_price_1',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_buy_price_1'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  }, // 申报前买方
  {
    show: false,
    gear: 1,
    id: '99201',
    minWidth: '100px',
    label: '申报前买方第一档数量',
    field: 'bo_buy_vol_1',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_buy_vol_1'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 2,
    id: '202',
    minWidth: '100px',
    label: '申报前买方第二档价格',
    field: 'bo_buy_price_2',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_buy_price_2'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 2,
    id: '99202',
    minWidth: '100px',
    label: '申报前买方第二档数量',
    field: 'bo_buy_vol_2',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_buy_vol_2'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 3,
    id: '203',
    minWidth: '100px',
    label: '申报前买方第三档价格',
    field: 'bo_buy_price_3',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_buy_price_3'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 3,
    id: '99203',
    minWidth: '100px',
    label: '申报前买方第三档数量',
    field: 'bo_buy_vol_3',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_buy_vol_3'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 4,
    id: '204',
    minWidth: '100px',
    label: '申报前买方第四档价格',
    field: 'bo_buy_price_4',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_buy_price_4'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 4,
    id: '99204',
    minWidth: '100px',
    label: '申报前买方第四档数量',
    field: 'bo_buy_vol_4',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_buy_vol_4'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 5,
    id: '205',
    minWidth: '100px',
    label: '申报前买方第五档价格',
    field: 'bo_buy_price_5',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_buy_price_5'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 5,
    id: '99205',
    minWidth: '100px',
    label: '申报前买方第五档数量',
    field: 'bo_buy_vol_5',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_buy_vol_5'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 6,
    id: '206',
    minWidth: '100px',
    label: '申报前买方第六档价格',
    field: 'bo_buy_price_6',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_buy_price_6'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 6,
    id: '99206',
    minWidth: '100px',
    label: '申报前买方第六档数量',
    field: 'bo_buy_vol_6',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_buy_vol_6'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 7,
    id: '207',
    minWidth: '100px',
    label: '申报前买方第七档价格',
    field: 'bo_buy_price_7',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_buy_price_7'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 7,
    id: '99207',
    minWidth: '100px',
    label: '申报前买方第七档数量',
    field: 'bo_buy_vol_7',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_buy_vol_7'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 8,
    id: '208',
    minWidth: '100px',
    label: '申报前买方第八档价格',
    field: 'bo_buy_price_8',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_buy_price_8'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 8,
    id: '99208',
    minWidth: '100px',
    label: '申报前买方第八档数量',
    field: 'bo_buy_vol_8',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_buy_vol_8'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 9,
    id: '209',
    minWidth: '100px',
    label: '申报前买方第九档价格',
    field: 'bo_buy_price_9',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_buy_price_9'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 9,
    id: '99209',
    minWidth: '100px',
    label: '申报前买方第九档数量',
    field: 'bo_buy_vol_9',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_buy_vol_9'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 10,
    id: '210',
    minWidth: '100px',
    label: '申报前买方第十档价格',
    field: 'bo_buy_price_10',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_buy_price_10'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 10,
    id: '99210',
    minWidth: '100px',
    label: '申报前买方第十档数量',
    field: 'bo_buy_vol_10',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_buy_vol_10'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  // 申报前卖方
  {
    show: false,
    gear: 1,
    id: '2201',
    minWidth: '100px',
    label: '申报前卖方第一档价格',
    field: 'bo_sell_price_1',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_sell_price_1'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 1,
    id: '992201',
    minWidth: '100px',
    label: '申报前卖方第一档数量',
    field: 'bo_sell_vol_1',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_sell_vol_1'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 2,
    id: '2202',
    minWidth: '100px',
    label: '申报前卖方第二档价格',
    field: 'bo_sell_price_2',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_sell_price_2'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 2,
    id: '992202',
    minWidth: '100px',
    label: '申报前卖方第二档数量',
    field: 'bo_sell_vol_2',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_sell_vol_2'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 3,
    id: '2203',
    minWidth: '100px',
    label: '申报前卖方第三档价格',
    field: 'bo_sell_price_3',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_sell_price_3'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 3,
    id: '992203',
    minWidth: '100px',
    label: '申报前卖方第三档数量',
    field: 'bo_sell_vol_3',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_sell_vol_3'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 4,
    id: '2204',
    minWidth: '100px',
    label: '申报前卖方第四档价格',
    field: 'bo_sell_price_4',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_sell_price_4'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 4,
    id: '992204',
    minWidth: '100px',
    label: '申报前卖方第四档数量',
    field: 'bo_sell_vol_4',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_sell_vol_4'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 5,
    id: '2205',
    minWidth: '100px',
    label: '申报前卖方第五档价格',
    field: 'bo_sell_price_5',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_sell_price_5'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 5,
    id: '992205',
    minWidth: '100px',
    label: '申报前卖方第五档数量',
    field: 'bo_sell_vol_5',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_sell_vol_5'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 6,
    id: '2206',
    minWidth: '100px',
    label: '申报前卖方第六档价格',
    field: 'bo_sell_price_6',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_sell_price_6'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 6,
    id: '992206',
    minWidth: '100px',
    label: '申报前卖方第六档数量',
    field: 'bo_sell_vol_6',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_sell_vol_6'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 7,
    id: '2207',
    minWidth: '100px',
    label: '申报前卖方第七档价格',
    field: 'bo_sell_price_7',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_sell_price_7'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 7,
    id: '992207',
    minWidth: '100px',
    label: '申报前卖方第七档数量',
    field: 'bo_sell_vol_7',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_sell_vol_7'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 8,
    id: '2208',
    minWidth: '100px',
    label: '申报前卖方第八档价格',
    field: 'bo_sell_price_8',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_sell_price_8'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 8,
    id: '992208',
    minWidth: '100px',
    label: '申报前卖方第八档数量',
    field: 'bo_sell_vol_8',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_sell_vol_8'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 9,
    id: '2209',
    minWidth: '100px',
    label: '申报前卖方第九档价格',
    field: 'bo_sell_price_9',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_sell_price_9'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 9,
    id: '992209',
    minWidth: '100px',
    label: '申报前卖方第九档数量',
    field: 'bo_sell_vol_9',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_sell_vol_9'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 10,
    id: '2210',
    minWidth: '100px',
    label: '申报前卖方第十档价格',
    field: 'bo_sell_price_10',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_sell_price_10'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 10,
    id: '992210',
    minWidth: '100px',
    label: '申报前卖方第十档数量',
    field: 'bo_sell_vol_10',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bo_sell_vol_10'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  // 申报后买方
  {
    show: false,
    gear: 1,
    id: '301',
    minWidth: '100px',
    label: '申报后买方第一档价格',
    field: 'ao_buy_price_1',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_buy_price_1'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 1,
    id: '99301',
    minWidth: '100px',
    label: '申报后买方第一档数量',
    field: 'ao_buy_vol_1',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_buy_vol_1'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 2,
    id: '302',
    minWidth: '100px',
    label: '申报后买方第二档价格',
    field: 'ao_buy_price_2',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_buy_price_2'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 2,
    id: '99302',
    minWidth: '100px',
    label: '申报后买方第二档数量',
    field: 'ao_buy_vol_2',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_buy_vol_2'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 3,
    id: '303',
    minWidth: '100px',
    label: '申报后买方第三档价格',
    field: 'ao_buy_price_3',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_buy_price_3'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 3,
    id: '99303',
    minWidth: '100px',
    label: '申报后买方第三档数量',
    field: 'ao_buy_vol_3',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_buy_vol_3'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 4,
    id: '304',
    minWidth: '100px',
    label: '申报后买方第四档价格',
    field: 'ao_buy_price_4',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_buy_price_4'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 4,
    id: '99304',
    minWidth: '100px',
    label: '申报后买方第四档数量',
    field: 'ao_buy_vol_4',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_buy_vol_4'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 5,
    id: '305',
    minWidth: '100px',
    label: '申报后买方第五档价格',
    field: 'ao_buy_price_5',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_buy_price_5'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 5,
    id: '99305',
    minWidth: '100px',
    label: '申报后买方第五档数量',
    field: 'ao_buy_vol_5',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_buy_vol_5'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 6,
    id: '306',
    minWidth: '100px',
    label: '申报后买方第六档价格',
    field: 'ao_buy_price_6',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_buy_price_6'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 6,
    id: '99306',
    minWidth: '100px',
    label: '申报后买方第六档数量',
    field: 'ao_buy_vol_6',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_buy_vol_6'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 7,
    id: '307',
    minWidth: '100px',
    label: '申报后买方第七档价格',
    field: 'ao_buy_price_7',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_buy_price_7'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 7,
    id: '99307',
    minWidth: '100px',
    label: '申报后买方第七档数量',
    field: 'ao_buy_vol_7',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_buy_vol_7'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 8,
    id: '308',
    minWidth: '100px',
    label: '申报后买方第八档价格',
    field: 'ao_buy_price_8',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_buy_price_8'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 8,
    id: '99308',
    minWidth: '100px',
    label: '申报后买方第八档数量',
    field: 'ao_buy_vol_8',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_buy_vol_8'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 9,
    id: '309',
    minWidth: '100px',
    label: '申报后买方第九档价格',
    field: 'ao_buy_price_9',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_buy_price_9'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 9,
    id: '99309',
    minWidth: '100px',
    label: '申报后买方第九档数量',
    field: 'ao_buy_vol_9',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_buy_vol_9'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 10,
    id: '310',
    minWidth: '100px',
    label: '申报后买方第十档价格',
    field: 'ao_buy_price_10',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_buy_price_10'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 10,
    id: '99310',
    minWidth: '100px',
    label: '申报后买方第十档数量',
    field: 'ao_buy_vol_10',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_buy_vol_10'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  // 申报后卖方
  {
    show: false,
    gear: 1,
    id: '3301',
    minWidth: '100px',
    label: '申报后卖方第一档价格',
    field: 'ao_sell_price_1',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_sell_price_1'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 1,
    id: '993301',
    minWidth: '100px',
    label: '申报后卖方第一档数量',
    field: 'ao_sell_vol_1',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_sell_vol_1'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 2,
    id: '3302',
    minWidth: '100px',
    label: '申报后卖方第二档价格',
    field: 'ao_sell_price_2',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_sell_price_2'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 2,
    id: '993302',
    minWidth: '100px',
    label: '申报后卖方第二档数量',
    field: 'ao_sell_vol_2',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_sell_vol_2'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 3,
    id: '3303',
    minWidth: '100px',
    label: '申报后卖方第三档价格',
    field: 'ao_sell_price_3',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_sell_price_3'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 3,
    id: '993303',
    minWidth: '100px',
    label: '申报后卖方第三档数量',
    field: 'ao_sell_vol_3',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_sell_vol_3'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 4,
    id: '3304',
    minWidth: '100px',
    label: '申报后卖方第四档价格',
    field: 'ao_sell_price_4',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_sell_price_4'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 4,
    id: '993304',
    minWidth: '100px',
    label: '申报后卖方第四档数量',
    field: 'ao_sell_vol_4',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_sell_vol_4'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 5,
    id: '3305',
    minWidth: '100px',
    label: '申报后卖方第五档价格',
    field: 'ao_sell_price_5',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_sell_price_5'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 5,
    id: '993305',
    minWidth: '100px',
    label: '申报后卖方第五档数量',
    field: 'ao_sell_vol_5',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_sell_vol_5'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 6,
    id: '3306',
    minWidth: '100px',
    label: '申报后卖方第六档价格',
    field: 'ao_sell_price_6',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_sell_price_6'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 6,
    id: '993306',
    minWidth: '100px',
    label: '申报后卖方第六档数量',
    field: 'ao_sell_vol_6',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_sell_vol_6'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 7,
    id: '3307',
    minWidth: '100px',
    label: '申报后卖方第七档价格',
    field: 'ao_sell_price_7',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_sell_price_7'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 7,
    id: '993307',
    minWidth: '100px',
    label: '申报后卖方第七档数量',
    field: 'ao_sell_vol_7',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_sell_vol_7'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 8,
    id: '3308',
    minWidth: '100px',
    label: '申报后卖方第八档价格',
    field: 'ao_sell_price_8',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_sell_price_8'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 8,
    id: '993308',
    minWidth: '100px',
    label: '申报后卖方第八档数量',
    field: 'ao_sell_vol_8',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_sell_vol_8'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 9,
    id: '3309',
    minWidth: '100px',
    label: '申报后卖方第九档价格',
    field: 'ao_sell_price_9',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_sell_price_9'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 9,
    id: '993309',
    minWidth: '100px',
    label: '申报后卖方第九档数量',
    field: 'ao_sell_vol_9',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_sell_vol_9'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 10,
    id: '3310',
    minWidth: '100px',
    label: '申报后卖方第十档价格',
    field: 'ao_sell_price_10',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_sell_price_10'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 10,
    id: '993310',
    minWidth: '100px',
    label: '申报后卖方第十档数量',
    field: 'ao_sell_vol_10',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'ao_sell_vol_10'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  // 撤单前买方
  {
    show: false,
    gear: 1,
    id: '401',
    minWidth: '100px',
    label: '撤单前买方第一档价格',
    field: 'bw_buy_price_1',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_buy_price_1'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 1,
    id: '99401',
    minWidth: '100px',
    label: '撤单前买方第一档数量',
    field: 'bw_buy_vol_1',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_buy_vol_1'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 2,
    id: '402',
    minWidth: '100px',
    label: '撤单前买方第二档价格',
    field: 'bw_buy_price_2',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_buy_price_2'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 2,
    id: '99402',
    minWidth: '100px',
    label: '撤单前买方第二档数量',
    field: 'bw_buy_vol_2',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_buy_vol_2'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 3,
    id: '403',
    minWidth: '100px',
    label: '撤单前买方第三档价格',
    field: 'bw_buy_price_3',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_buy_price_3'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 3,
    id: '99403',
    minWidth: '100px',
    label: '撤单前买方第三档数量',
    field: 'bw_buy_vol_3',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_buy_vol_3'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 4,
    id: '404',
    minWidth: '100px',
    label: '撤单前买方第四档价格',
    field: 'bw_buy_price_4',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_buy_price_4'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 4,
    id: '99404',
    minWidth: '100px',
    label: '撤单前买方第四档数量',
    field: 'bw_buy_vol_4',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_buy_vol_4'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 5,
    id: '405',
    minWidth: '100px',
    label: '撤单前买方第五档价格',
    field: 'bw_buy_price_5',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_buy_price_5'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 5,
    id: '99405',
    minWidth: '100px',
    label: '撤单前买方第五档数量',
    field: 'bw_buy_vol_5',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_buy_vol_5'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 6,
    id: '406',
    minWidth: '100px',
    label: '撤单前买方第六档价格',
    field: 'bw_buy_price_6',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_buy_price_6'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 6,
    id: '99406',
    minWidth: '100px',
    label: '撤单前买方第六档数量',
    field: 'bw_buy_vol_6',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_buy_vol_6'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 7,
    id: '407',
    minWidth: '100px',
    label: '撤单前买方第七档价格',
    field: 'bw_buy_price_7',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_buy_price_7'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 7,
    id: '99407',
    minWidth: '100px',
    label: '撤单前买方第七档数量',
    field: 'bw_buy_vol_7',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_buy_vol_7'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 8,
    id: '408',
    minWidth: '100px',
    label: '撤单前买方第八档价格',
    field: 'bw_buy_price_8',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_buy_price_8'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 8,
    id: '99408',
    minWidth: '100px',
    label: '撤单前买方第八档数量',
    field: 'bw_buy_vol_8',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_buy_vol_8'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 9,
    id: '409',
    minWidth: '100px',
    label: '撤单前买方第九档价格',
    field: 'bw_buy_price_9',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_buy_price_9'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 9,
    id: '99409',
    minWidth: '100px',
    label: '撤单前买方第九档数量',
    field: 'bw_buy_vol_9',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_buy_vol_9'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 10,
    id: '410',
    minWidth: '100px',
    label: '撤单前买方第十档价格',
    field: 'bw_buy_price_10',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_buy_price_10'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 10,
    id: '99410',
    minWidth: '100px',
    label: '撤单前买方第十档数量',
    field: 'bw_buy_vol_10',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_buy_vol_10'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  // 撤单前卖方
  {
    show: false,
    gear: 1,
    id: '4401',
    minWidth: '100px',
    label: '撤单前卖方第一档价格',
    field: 'bw_sell_price_1',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_sell_price_1'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 1,
    id: '994401',
    minWidth: '100px',
    label: '撤单前卖方第一档数量',
    field: 'bw_sell_vol_1',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_sell_vol_1'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 2,
    id: '4402',
    minWidth: '100px',
    label: '撤单前卖方第二档价格',
    field: 'bw_sell_price_2',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_sell_price_2'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 2,
    id: '994402',
    minWidth: '100px',
    label: '撤单前卖方第二档数量',
    field: 'bw_sell_vol_2',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_sell_vol_2'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 3,
    id: '4403',
    minWidth: '100px',
    label: '撤单前卖方第三档价格',
    field: 'bw_sell_price_3',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_sell_price_3'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 3,
    id: '994403',
    minWidth: '100px',
    label: '撤单前卖方第三档数量',
    field: 'bw_sell_vol_3',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_sell_vol_3'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 4,
    id: '4404',
    minWidth: '100px',
    label: '撤单前卖方第四档价格',
    field: 'bw_sell_price_4',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_sell_price_4'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 4,
    id: '994404',
    minWidth: '100px',
    label: '撤单前卖方第四档数量',
    field: 'bw_sell_vol_4',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_sell_vol_4'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 5,
    id: '4405',
    minWidth: '100px',
    label: '撤单前卖方第五档价格',
    field: 'bw_sell_price_5',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_sell_price_5'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 5,
    id: '994405',
    minWidth: '100px',
    label: '撤单前卖方第五档数量',
    field: 'bw_sell_vol_5',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_sell_vol_5'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 6,
    id: '4406',
    minWidth: '100px',
    label: '撤单前卖方第六档价格',
    field: 'bw_sell_price_6',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_sell_price_6'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 6,
    id: '994406',
    minWidth: '100px',
    label: '撤单前卖方第六档数量',
    field: 'bw_sell_vol_6',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_sell_vol_6'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 7,
    id: '4407',
    minWidth: '100px',
    label: '撤单前卖方第七档价格',
    field: 'bw_sell_price_7',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_sell_price_7'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 7,
    id: '994407',
    minWidth: '100px',
    label: '撤单前卖方第七档数量',
    field: 'bw_sell_vol_7',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_sell_vol_7'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 8,
    id: '4408',
    minWidth: '100px',
    label: '撤单前卖方第八档价格',
    field: 'bw_sell_price_8',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_sell_price_8'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 8,
    id: '994408',
    minWidth: '100px',
    label: '撤单前卖方第八档数量',
    field: 'bw_sell_vol_8',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_sell_vol_8'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 9,
    id: '4409',
    minWidth: '100px',
    label: '撤单前卖方第九档价格',
    field: 'bw_sell_price_9',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_sell_price_9'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 9,
    id: '994409',
    minWidth: '100px',
    label: '撤单前卖方第九档数量',
    field: 'bw_sell_vol_9',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_sell_vol_9'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 10,
    id: '4410',
    minWidth: '100px',
    label: '撤单前卖方第十档价格',
    field: 'bw_sell_price_10',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_sell_price_10'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 10,
    id: '994410',
    minWidth: '100px',
    label: '撤单前卖方第十档数量',
    field: 'bw_sell_vol_10',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'bw_sell_vol_10'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  // 撤单后买方
  {
    show: false,
    gear: 1,
    id: '501',
    minWidth: '100px',
    label: '撤单后买方第一档价格',
    field: 'aw_buy_price_1',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_buy_price_1'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 1,
    id: '99501',
    minWidth: '100px',
    label: '撤单后买方第一档数量',
    field: 'aw_buy_vol_1',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_buy_vol_1'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 2,
    id: '502',
    minWidth: '100px',
    label: '撤单后买方第二档价格',
    field: 'aw_buy_price_2',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_buy_price_2'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 2,
    id: '99502',
    minWidth: '100px',
    label: '撤单后买方第二档数量',
    field: 'aw_buy_vol_2',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_buy_vol_2'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 3,
    id: '503',
    minWidth: '100px',
    label: '撤单后买方第三档价格',
    field: 'aw_buy_price_3',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_buy_price_3'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 3,
    id: '99503',
    minWidth: '100px',
    label: '撤单后买方第三档数量',
    field: 'aw_buy_vol_3',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_buy_vol_3'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 4,
    id: '504',
    minWidth: '100px',
    label: '撤单后买方第四档价格',
    field: 'aw_buy_price_4',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_buy_price_4'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 4,
    id: '99504',
    minWidth: '100px',
    label: '撤单后买方第四档数量',
    field: 'aw_buy_vol_4',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_buy_vol_4'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 5,
    id: '505',
    minWidth: '100px',
    label: '撤单后买方第五档价格',
    field: 'aw_buy_price_5',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_buy_price_5'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 5,
    id: '99505',
    minWidth: '100px',
    label: '撤单后买方第五档数量',
    field: 'aw_buy_vol_5',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_buy_vol_5'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 6,
    id: '506',
    minWidth: '100px',
    label: '撤单后买方第六档价格',
    field: 'aw_buy_price_6',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_buy_price_6'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 6,
    id: '99506',
    minWidth: '100px',
    label: '撤单后买方第六档数量',
    field: 'aw_buy_vol_6',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_buy_vol_6'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 7,
    id: '507',
    minWidth: '100px',
    label: '撤单后买方第七档价格',
    field: 'aw_buy_price_7',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_buy_price_7'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 7,
    id: '99507',
    minWidth: '100px',
    label: '撤单后买方第七档数量',
    field: 'aw_buy_vol_7',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_buy_vol_7'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 8,
    id: '508',
    minWidth: '100px',
    label: '撤单后买方第八档价格',
    field: 'aw_buy_price_8',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_buy_price_8'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 8,
    id: '99508',
    minWidth: '100px',
    label: '撤单后买方第八档数量',
    field: 'aw_buy_vol_8',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_buy_vol_8'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 9,
    id: '509',
    minWidth: '100px',
    label: '撤单后买方第九档价格',
    field: 'aw_buy_price_9',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_buy_price_9'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 9,
    id: '99509',
    minWidth: '100px',
    label: '撤单后买方第九档数量',
    field: 'aw_buy_vol_9',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_buy_vol_9'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 10,
    id: '510',
    minWidth: '100px',
    label: '撤单后买方第十档价格',
    field: 'aw_buy_price_10',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_buy_price_10'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 10,
    id: '99510',
    minWidth: '100px',
    label: '撤单后买方第十档数量',
    field: 'aw_buy_vol_10',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_buy_vol_10'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  // 撤单后卖方
  {
    show: false,
    gear: 1,
    id: '5501',
    minWidth: '100px',
    label: '撤单后卖方第一档价格',
    field: 'aw_sell_price_1',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_sell_price_1'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 1,
    id: '995501',
    minWidth: '100px',
    label: '撤单后卖方第一档数量',
    field: 'aw_sell_vol_1',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_sell_vol_1'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 2,
    id: '5502',
    minWidth: '100px',
    label: '撤单后卖方第二档价格',
    field: 'aw_sell_price_2',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_sell_price_2'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 2,
    id: '995502',
    minWidth: '100px',
    label: '撤单后卖方第二档数量',
    field: 'aw_sell_vol_2',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_sell_vol_2'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 3,
    id: '5503',
    minWidth: '100px',
    label: '撤单后卖方第三档价格',
    field: 'aw_sell_price_3',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_sell_price_3'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 3,
    id: '995503',
    minWidth: '100px',
    label: '撤单后卖方第三档数量',
    field: 'aw_sell_vol_3',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_sell_vol_3'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 4,
    id: '5504',
    minWidth: '100px',
    label: '撤单后卖方第四档价格',
    field: 'aw_sell_price_4',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_sell_price_4'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 4,
    id: '995504',
    minWidth: '100px',
    label: '撤单后卖方第四档数量',
    field: 'aw_sell_vol_4',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_sell_vol_4'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 5,
    id: '5505',
    minWidth: '100px',
    label: '撤单后卖方第五档价格',
    field: 'aw_sell_price_5',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_sell_price_5'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 5,
    id: '995505',
    minWidth: '100px',
    label: '撤单后卖方第五档数量',
    field: 'aw_sell_vol_5',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_sell_vol_5'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 6,
    id: '5506',
    minWidth: '100px',
    label: '撤单后卖方第六档价格',
    field: 'aw_sell_price_6',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_sell_price_6'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 6,
    id: '995506',
    minWidth: '100px',
    label: '撤单后卖方第六档数量',
    field: 'aw_sell_vol_6',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_sell_vol_6'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 7,
    id: '5507',
    minWidth: '100px',
    label: '撤单后卖方第七档价格',
    field: 'aw_sell_price_7',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_sell_price_7'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 7,
    id: '995507',
    minWidth: '100px',
    label: '撤单后卖方第七档数量',
    field: 'aw_sell_vol_7',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_sell_vol_7'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 8,
    id: '5508',
    minWidth: '100px',
    label: '撤单后卖方第八档价格',
    field: 'aw_sell_price_8',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_sell_price_8'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 8,
    id: '995508',
    minWidth: '100px',
    label: '撤单后卖方第八档数量',
    field: 'aw_sell_vol_8',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_sell_vol_8'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 9,
    id: '5509',
    minWidth: '100px',
    label: '撤单后卖方第九档价格',
    field: 'aw_sell_price_9',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_sell_price_9'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 9,
    id: '995509',
    minWidth: '100px',
    label: '撤单后卖方第九档数量',
    field: 'aw_sell_vol_9',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_sell_vol_9'),
    formatter: complexQueryDec0,
    format: '#,##0'
  },
  {
    show: false,
    gear: 10,
    id: '5510',
    minWidth: '100px',
    label: '撤单后卖方第十档价格',
    field: 'aw_sell_price_10',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_sell_price_10'),
    formatter: complexQueryDec5,
    format: '#,##0.00000'
  },
  {
    show: false,
    gear: 10,
    id: '995510',
    minWidth: '100px',
    label: '撤单后卖方第十档数量',
    field: 'aw_sell_vol_10',
    align: 'right',
    sortable: true,
    sortMethod: Vue.prototype.gfnSortColByNumber.bind(Vue, 'aw_sell_vol_10'),
    formatter: complexQueryDec0,
    format: '#,##0'
  }
]
